// script.js
const filmes = {
  drama: [
    { nome: 'A Fantástica Fábrica de Chocolate', imagem: 'imagem1.jpg', classificacao: 'Livre', ano: 0, duracao: '0', sinopse: 'Willy Wonka (Johnny Depp) é o excêntrico dono da maior fábrica de doces do planeta, que decide realizar um concurso mundial para escolher um herdeiro para seu império. Cinco crianças de sorte, entre elas Charlie Bucket (Freddie Highmore), encontram um convite dourado em barras de chocolate Wonka e com isso ganham uma visita guiada pela lendária fábrica de chocolate, que não era visitada por ninguém há 15 anos. Encantado com as maravilhas da fábrica, Charlie fica cada vez mais fascinado com a visita.', trailer: 'linkfilme1' },
    { nome: 'Divertida Mente', imagem: 'imagem2.jpg', classificacao: '10', ano: 0, duracao: '0', sinopse: 'Riley é uma garota divertida de 11 anos de idade, que deve enfrentar mudanças importantes em sua vida quando seus pais decidem deixar a sua cidade natal, no estado de Minnesota, para viver em San Francisco. Dentro do cérebro de Riley, convivem várias emoções diferentes, como a Alegria, o Medo, a Raiva, o Nojinho e a Tristeza. A líder deles é Alegria, que se esforça bastante para fazer com que a vida de Riley seja sempre feliz.', trailer: 'linkfilme2' },
    { nome: 'O Menino Do Pijama Listrado', imagem: 'imagem3.jpg', classificacao: '12', ano: 0, duracao: '0', sinopse: 'Alemanha, Segunda Guerra Mundial. O menino Bruno (Asa Butterfield), de 8 anos, é filho de um oficial nazista (David Tewlis) que assume um cargo importante em um campo de concentração. Sem saber realmente o que seu pai faz, ele deixa Berlim e se muda com ele e a mãe (Vera Farmiga) para uma área isolada, onde não há muito o que fazer para uma criança com a idade dele.', trailer: 'linkfilme3' },
    { nome: 'A Menina que Roubava Livros', imagem: 'imagem4.jpg', classificacao: '14', ano: 0, duracao: '0', sinopse: 'Durante a Segunda Guerra Mundial, uma jovem garota chamada Liesel Meminger (Sophie Nélisse) sobrevive fora de Munique através dos livros que ela rouba. Ajudada por seu pai adotivo (Geoffrey Rush), ela aprende a ler e partilhar livros com seus amigos, incluindo um homem judeu (Ben Schnetzer) que vive na clandestinidade em sua casa.', trailer: 'linkfilme4' },
    { nome: 'O Regresso', imagem: 'imagem5.jpg', classificacao: '16', ano: 0, duracao: '0', sinopse: '1822. Hugh Glass (Leonardo DiCaprio) parte para o oeste americano disposto a ganhar dinheiro caçando. Atacado por um urso, fica seriamente ferido e é abandonado à própria sorte pelo parceiro John Fitzgerald (Tom Hardy), que ainda rouba seus pertences. Entretanto, mesmo com toda adversidade, Glass consegue sobreviver e inicia uma árdua jornada em busca de vingança.', trailer: 'linkfilme5' }
  ],
  suspense: [
    { nome: 'Coraline e o Mundo Secreto', imagem: 'imagem6.jpg', classificacao: 'Livre', ano: 0, duracao: '0', sinopse: 'Um mundo secreto se abre e realiza todos os seus desejos, mas com um preço. Caroline Jones (Dakota Fanning) precisa se adaptar à sua nova realidade e nova casa em Oregon. Incrivelmente entediada e sem a atenção dos pais, Coraline esbarra um dia com um gato preto e o neto da senhoria, que lhe entrega uma boneca de pano da jovem e lhe apresenta uma porta secreta.', trailer: 'linkfilme6' },
    { nome: 'Convenção das Bruxas', imagem: 'imagem7.jpg', classificacao: '10', ano: 0, duracao: '0', sinopse: 'Após a morte do pai, Luke (Jasen Fisher), 10 anos, é levado por sua avó (Mai Zetterling) para um hotel na Inglaterra. Lá o garoto descobre que um grupo de bruxas está fazendo uma convenção e que pretendem transformar todas as crianças do mundo em ratos.', trailer: 'linkfilme7' },
    { nome: 'Identidades em Jogo', imagem: 'imagem8.jpg', classificacao: '12', ano: 0, duracao: '0', sinopse: 'Um grupo de amigos da faculdade se reúne para celebrar o noivado de um deles na véspera da cerimônia. Uma despedida de solteiro divertida na mansão reclusa de sua mãe era o que Reuben (Devon Terrell) desejava. Mas os planos de uma noite animada mudam quando, de surpresa, um colega distante da turma surge com uma maleta misteriosa contendo um aparelho capaz de realizar troca de corpos.', trailer: 'linkfilme8' },
    { nome: 'Desaparecidos na Noite', imagem: 'imagem9.jpg', classificacao: '14', ano: 0, duracao: '0', sinopse: 'Pietro (Riccardo Scamarcio), um homem com um passado tempestuoso, e sua esposa Elena (Annabelle Wallis) enfrentam uma disputa pela custódia dos filhos. Certo dia, suas crianças desaparecem misteriosamente e a busca por elas se transforma em um jogo desesperado, envolvendo um sequestro e uma quantia milionária.', trailer: 'linkfilme9' },
    { nome: 'Fuja', imagem: 'imagem10.jpg', classificacao: '16', ano: 0, duracao: '0', sinopse: 'Chloe (Kiera Allen) é uma adolescente que sofre de inúmeras doenças, inclusive paralisia, que a colocou em uma cadeira de rodas. Ela é educada em casa por sua mãe, Diane (Sarah Paulson), e aguarda a carta de resposta da faculdade. No entanto, o comportamento estranho apresentado pela matriarca começa a deixar a jovem desconfiada de que algo está errado.', trailer: 'linkfilme10' }
  ],
  terror: [
    { nome: 'A Casa Monstro', imagem: 'imagem11.jpg', classificacao: 'Livre', ano: 0, duracao: '0', sinopse: 'DJ Walters (Mitchel Musso) é um garoto de 12 anos que acredita que há algo de estranho na casa do velho Nebbercracker (Steve Buscemi). Tudo que passa perto da casa simplesmente desaparece. Durante a véspera do Dia das Bruxas, DJ e seu amigo Chowder (Sam Lester) descobrem que a casa tem vida própria e planejam um plano para destruí-la.', trailer: 'linkfilme11' },
    { nome: 'O Estranho Mundo de Jack', imagem: 'imagem12.jpg', classificacao: '10', ano: 0, duracao: '0', sinopse: 'Jack Skellington (Chris Sarandon) é um ser fantástico que vive na Cidade do Halloween. Cansado de repetir os mesmos rituais de Halloween, Jack atravessa um portal e encontra o Natal. Ele decide sequestrar o Papai Noel e celebrar o Natal de uma maneira muito peculiar.', trailer: 'linkfilme12' },
    { nome: 'ParaNorman', imagem: 'imagem13.jpg', classificacao: '12', ano: 0, duracao: '0', sinopse: 'Norman Babcock (Kodi Smit-McPhee) é um garoto que consegue ver e falar com os mortos. Quando a cidade é ameaçada por uma maldição, Norman e seu amigo Neil tentam impedir que os mortos se levantem e causem caos.', trailer: 'linkfilme13' },
    { nome: 'It: A Coisa', imagem: 'imagem14.jpg', classificacao: '14', ano: 0, duracao: '0', sinopse: 'Em Derry, um grupo de sete adolescentes enfrenta um palhaço demoníaco chamado Pennywise, responsável pelo desaparecimento de crianças na cidade. Juntos, eles devem enfrentar seus maiores medos para derrotar a criatura.', trailer: 'linkfilme14' },
    { nome: 'A Orfã', imagem: 'imagem15.jpg', classificacao: '16', ano: 0, duracao: '0', sinopse: 'Kate (Vera Farmiga) e John (Peter Sarsgaard) adotam uma menina chamada Esther (Isabelle Fuhrman). No entanto, estranhos acontecimentos começam a acontecer, fazendo com que Kate desconfie de que Esther esconde um segredo sombrio.', trailer: 'linkfilme15' }
  ]
};

let idadeUsuario = 0;

function inserirNome() {
  let nomeUsuario = prompt("Qual o seu nome?");
  let elemento = document.querySelector("#nome-usuario");
  elemento.textContent = `Olá, ${nomeUsuario}! Espero te ajudar a escolher um filme
